import { db } from '../../db.js';

const CLUBS = [
  {
    id: 'nahoda-fc',
    slug: 'nahoda-fc',
    name: 'Náhoda FC',
    shortName: 'Náhoda',
    city: null,
    location: 'Hřiště za hasičárnou',
    note: 'Klub, který nikdy neměl postoupit. Bohužel postoupil.',
    colors: 'zelená, krémová, zlatá',
    motto: 'VAR nemáme, hraj dál.',
    description: 'Náhoda FC je klub, který se do Osmé ligy nedostal výkonem, ale okolnostmi — a od té doby se snaží dokázat, že i omyl může mít tabulkové ambice.',
    seasonComment: 'Když míč odskočí správným směrem, tým tomu říká taktika, když špatným, tak rozhodčí stejně nic neviděl.',
    banner: '/banners/nahoda_banner.webp',
    logo: null,
    primaryColor: '#063f24',
    secondaryColor: '#d8ad45',
    sortOrder: 1,
  },
  {
    id: 'tj-sokol-tupoljany',
    slug: 'tj-sokol-tupoljany',
    name: 'TJ Sokol Tupoljany',
    shortName: 'Tupoljany',
    city: null,
    location: 'Sokolské hřiště u remízku',
    note: 'Soupeř z posledního utkání. Ještě pořád počítá góly.',
    colors: 'červená a bílá',
    motto: 'Když je míč kulatý, musí někam letět.',
    description: 'TJ Sokol Tupoljany hraje fotbal přímočaře: když je míč kulatý, je potřeba ho někam poslat, ideálně směrem, kde stojí méně soupeřů.',
    seasonComment: 'Do sezony vstoupili Tupoljanští s energií, která by stačila i na dva poločasy navíc, jen se zatím řeší, kdo na ně má čas.',
    banner: '/banners/tj_sokol_tupoljany.webp',
    logo: null,
    primaryColor: null,
    secondaryColor: null,
    sortOrder: 2,
  },
  {
    id: 'sk-dolni-lhota',
    slug: 'sk-dolni-lhota',
    name: 'SK Dolní Lhota',
    shortName: 'Dolní Lhota',
    city: null,
    location: 'Areál Pod Lípou',
    note: 'Solidní tým ze Lhoty. Lhoty je v kraji víc.',
    colors: 'modrá a bílá',
    motto: 'Doma se body neztrácí, jen občas zapomenou.',
    description: 'SK Dolní Lhota je tým, který umí z každého zápasu udělat lokální událost, zvlášť když přijde víc lidí než hráčů na lavičku.',
    seasonComment: 'Sezona vypadá nadějně, pokud se podaří udržet obranu, kádr a síť v brance pohromadě.',
    banner: '/banners/sk_dolni_lhota.webp',
    logo: null,
    primaryColor: null,
    secondaryColor: null,
    sortOrder: 3,
  },
  {
    id: 'fk-parezov',
    slug: 'fk-parezov',
    name: 'FK Pařezov',
    shortName: 'Pařezov',
    city: null,
    location: 'Hřiště U Starého pařezu',
    note: 'Tým, který bere domácí prostředí doslova.',
    colors: 'hnědá a zelená',
    motto: 'Kořeny máme hluboko, skluz ještě níž.',
    description: 'FK Pařezov staví hru na tvrdém středu hřiště, dlouhých nákopech a přesvědčení, že každý odraz je součástí taktické přípravy.',
    seasonComment: 'Letos chtějí ukázat, že i tým z pařezů může růst, pokud ho nikdo předčasně neokopne.',
    banner: '/banners/fk_parezov.webp',
    logo: null,
    primaryColor: null,
    secondaryColor: null,
    sortOrder: 4,
  },
  {
    id: 'tj-jiskra-vetrovy',
    slug: 'tj-jiskra-vetrovy',
    name: 'TJ Jiskra Větrovy',
    shortName: 'Větrovy',
    city: null,
    location: 'Větrná aréna',
    note: 'Hráči z kopce. Vítr jim přidává páté třetinky.',
    colors: 'žlutá a černá',
    motto: 'Když fouká, hrajeme po větru.',
    description: 'TJ Jiskra Větrovy je klub, který umí začít zápas v tempu, jako by ho hnala bouřka od západu.',
    seasonComment: 'V sezoně jim nechybí nadšení ani pohyb, jen občas není jisté, jestli běží za míčem, nebo je prostě odnáší vítr.',
    banner: '/banners/tj_jiskra_vetrovy.webp',
    logo: null,
    primaryColor: null,
    secondaryColor: null,
    sortOrder: 5,
  },
  {
    id: 'sokol-mokra-stran',
    slug: 'sokol-mokra-stran',
    name: 'Sokol Mokrá Stráň',
    shortName: 'Mokrá Stráň',
    city: null,
    location: 'Hřiště Na Louži',
    note: 'Hřiště mokré za každého počasí. Lajny volitelné.',
    colors: 'modrá a zelená',
    motto: 'Technika klouže, srdce drží.',
    description: 'Sokol Mokrá Stráň má domácí hřiště, kde se technika s míčem rychle mění v boj o rovnováhu.',
    seasonComment: 'Klub letos spoléhá na týmového ducha, pevné kolíky v kopačkách a víru, že déšť padá na obě mužstva stejně.',
    banner: '/banners/sokol_mokra_stran.webp',
    logo: null,
    primaryColor: null,
    secondaryColor: null,
    sortOrder: 6,
  },
  {
    id: 'sk-nove-drny',
    slug: 'sk-nove-drny',
    name: 'SK Nové Drny',
    shortName: 'Nové Drny',
    city: null,
    location: 'Stadion Nový pažit',
    note: 'Nové drny, starý fotbal. Kombinace funguje.',
    colors: 'zelená a bílá',
    motto: 'Rosteme odspodu.',
    description: 'SK Nové Drny je mladě působící tým, který se nebojí hrát odvážně, i když se míč občas rozhodne držet víc trávníku než plánu.',
    seasonComment: 'V sezoně chtějí potvrdit, že nový drn nemusí být jen povrch, ale i začátek nové klubové éry.',
    banner: '/banners/sk_nove_drny.webp',
    logo: null,
    primaryColor: null,
    secondaryColor: null,
    sortOrder: 7,
  },
  {
    id: 'fk-zelena-mezna',
    slug: 'fk-zelena-mezna',
    name: 'FK Zelená Mezná',
    shortName: 'Zelená Mezná',
    city: null,
    location: 'Hřiště Na Mezi',
    note: 'Zelení z mezí. Barvy mají jednu výhodu — splývají s hřištěm.',
    colors: 'zelená a žlutá',
    motto: 'Za čárou začíná náš presink.',
    description: 'FK Zelená Mezná je klub z kraje, kde se fotbal hraje s výhledem do polí a s vědomím, že pro každý míč se někdo musí dojít.',
    seasonComment: 'Letošní sezona je pro ně příležitost ukázat, že hranice hřiště nejsou hranice ambicí.',
    banner: '/banners/fk_zelena_mezna.webp',
    logo: null,
    primaryColor: null,
    secondaryColor: null,
    sortOrder: 8,
  },
  {
    id: 'tj-slavoj-brodek',
    slug: 'tj-slavoj-brodek',
    name: 'TJ Slavoj Brodek',
    shortName: 'Brodek',
    city: null,
    location: 'Brodecký plácek',
    note: 'Brodek má tradici. Trochu zaprášenou, ale tradici.',
    colors: 'vínová a bílá',
    motto: 'Když to nejde krásně, půjde to okresně.',
    description: 'TJ Slavoj Brodek patří mezi týmy, které možná nepřekvapí rychlostí, ale umí soupeře unavit tím, že se pořád vrací do soubojů.',
    seasonComment: 'Do sezony jdou s poctivostí, tvrdou prací a plánem, že když už se nedá vyhrát krásně, dá se vyhrát okresně.',
    banner: '/banners/tj_slavoj_brodek.webp',
    logo: null,
    primaryColor: null,
    secondaryColor: null,
    sortOrder: 9,
  },
  {
    id: 'fc-kamenice',
    slug: 'fc-kamenice',
    name: 'FC Kamenice',
    shortName: 'Kamenice',
    city: null,
    location: 'Kamenický stadionek',
    note: 'Tvrdý tým. Tvrdé hřiště. Tvrdé míče.',
    colors: 'šedá a modrá',
    motto: 'Tvrdě, jednoduše, bez zbytečných kudrlinek.',
    description: 'FC Kamenice je tým pevný jako jeho název — občas nehybný, ale když se rozjede, těžko se zastavuje.',
    seasonComment: 'V aktuální sezoně sází na jednoduchý fotbal, důraz v osobních soubojích a nadšení fanoušků, kteří už viděli horší věci než bezbrankovou remízu.',
    banner: '/banners/fc_kamenice.webp',
    logo: null,
    primaryColor: null,
    secondaryColor: null,
    sortOrder: 10,
  },
  {
    id: 'tj-dynamo-loucany',
    slug: 'tj-dynamo-loucany',
    name: 'TJ Dynamo Loučany',
    shortName: 'Loučany',
    city: null,
    location: 'Loučanská louka',
    note: 'Dynamo z Loučan. Energie přichází a odchází.',
    colors: 'oranžová a černá',
    motto: 'Energie máme dost, góly doháníme.',
    description: 'TJ Dynamo Loučany má v názvu energii a na hřišti snahu ji nějak proměnit v góly.',
    seasonComment: 'Letos chtějí hrát aktivněji, odvážněji a pokud možno tak, aby se po zápase nemluvilo jen o občerstvení.',
    banner: '/banners/tj_dynamo_loucany.webp',
    logo: null,
    primaryColor: null,
    secondaryColor: null,
    sortOrder: 11,
  },
];

export async function seedClubs(): Promise<void> {
  console.log('[seedClubs] starting...');
  for (const club of CLUBS) {
    await db.osmaClub.upsert({
      where: { id: club.id },
      update: {
        slug: club.slug,
        name: club.name,
        shortName: club.shortName,
        city: club.city,
        location: club.location,
        note: club.note,
        colors: club.colors,
        motto: club.motto,
        description: club.description,
        seasonComment: club.seasonComment,
        banner: club.banner,
        logo: club.logo,
        primaryColor: club.primaryColor,
        secondaryColor: club.secondaryColor,
        sortOrder: club.sortOrder,
      },
      create: club,
    });
    console.log(`[seedClubs] upserted: ${club.slug}`);
  }
  console.log('[seedClubs] done.');
}
